### ISSUE TITLE
Package 'tensorflow-macos' is listed as a dependency of itself

### ISSUE THREAD

**Issue by marygiotandoi** [tensorflow/recommenders#713]
I am building the local environment of a `Python` project, on a MacBook Pro (Apple M1 Max). However, I cannot install anymore `tensorflow-recommenders = "~=0.7.3"` using `poetry`.

I'm getting the following error:
> $> poetry lock --no-cache                                                                                                    
> Creating virtualenv <path to venv>
> Updating dependencies
> Resolving dependencies... (4.4s)
> 
> Package 'tensorflow-macos' is listed as a dependency of itself.

I'm using the following versions:
- Python 3.11.1
- Poetry: 1.8.2
- Pip: 24.0 

To reproduce this, create an empty directory, make sure you have `Python` and `poetry` setup, paste the following as your initial `pyproject.toml`

```toml
[tool.poetry]
package-mode = false
name = "project-name"
description = "Project description."

[tool.poetry.dependencies]
python = "~=3.11.0"
tensorflow-recommenders = "~=0.7.3"
```

And then run

`poetry lock --no-cache`
